[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = cmsis
upload_protocol = stlink
debug_tool = stlink

build_flags =
    -O3
    -ffast-math
    -funroll-loops
    -fomit-frame-pointer
    -Wl,-u,_printf_float
    -specs=nano.specs
    -specs=nosys.specs
